/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package myApplicationDesktop;

import java.awt.Image;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Admin
 */
public class XCalculator extends javax.swing.JFrame {

    /**
     * Creates new form XCalculator
     */
    int positionX = 0; int positionY = 0;
    ArrayList<String> addNum = new ArrayList<String>();
    int num;
    boolean clearField;
    int calculate;
    public XCalculator() {
        initComponents();
       this.setTitle("XCalculator");
       this.setResizable(false);
       this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
      
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        eightBtn = new javax.swing.JButton();
        multBtn = new javax.swing.JButton();
        nineBtn = new javax.swing.JButton();
        sevenBtn = new javax.swing.JButton();
        twoBtn = new javax.swing.JButton();
        sumBtn = new javax.swing.JButton();
        getResultBtn = new javax.swing.JButton();
        dividBtn = new javax.swing.JButton();
        substracBtn = new javax.swing.JButton();
        fourBtn = new javax.swing.JButton();
        oneBtn = new javax.swing.JButton();
        sixBtn = new javax.swing.JButton();
        threeBtn = new javax.swing.JButton();
        fiveBtn = new javax.swing.JButton();
        field_number = new javax.swing.JTextField();
        Jprogres = new javax.swing.JProgressBar();
        deleteBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_calc = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextField2.setText("jTextField2");

        jPanel2.setBackground(new java.awt.Color(119, 119, 119));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eightBtn.setBackground(new java.awt.Color(255, 255, 255));
        eightBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eightBtn.setForeground(new java.awt.Color(0, 0, 0));
        eightBtn.setText("8");
        eightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightBtnActionPerformed(evt);
            }
        });
        jPanel3.add(eightBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 58, 43));

        multBtn.setBackground(new java.awt.Color(255, 255, 255));
        multBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        multBtn.setForeground(new java.awt.Color(0, 0, 0));
        multBtn.setText("*");
        multBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multBtnActionPerformed(evt);
            }
        });
        jPanel3.add(multBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 58, 43));

        nineBtn.setBackground(new java.awt.Color(255, 255, 255));
        nineBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nineBtn.setForeground(new java.awt.Color(0, 0, 0));
        nineBtn.setText("9");
        nineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineBtnActionPerformed(evt);
            }
        });
        jPanel3.add(nineBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 58, 43));

        sevenBtn.setBackground(new java.awt.Color(255, 255, 255));
        sevenBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sevenBtn.setForeground(new java.awt.Color(0, 0, 0));
        sevenBtn.setText("7");
        sevenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenBtnActionPerformed(evt);
            }
        });
        jPanel3.add(sevenBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 58, 43));

        twoBtn.setBackground(new java.awt.Color(255, 255, 255));
        twoBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        twoBtn.setForeground(new java.awt.Color(0, 0, 0));
        twoBtn.setText("2");
        twoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoBtnActionPerformed(evt);
            }
        });
        jPanel3.add(twoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 58, 43));

        sumBtn.setBackground(new java.awt.Color(255, 255, 255));
        sumBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sumBtn.setForeground(new java.awt.Color(0, 0, 0));
        sumBtn.setText("+");
        sumBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumBtnActionPerformed(evt);
            }
        });
        jPanel3.add(sumBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 58, 43));

        getResultBtn.setBackground(new java.awt.Color(255, 255, 255));
        getResultBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getResultBtn.setForeground(new java.awt.Color(0, 0, 0));
        getResultBtn.setText("=");
        getResultBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getResultBtnActionPerformed(evt);
            }
        });
        jPanel3.add(getResultBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 58, 43));

        dividBtn.setBackground(new java.awt.Color(255, 255, 255));
        dividBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dividBtn.setForeground(new java.awt.Color(0, 0, 0));
        dividBtn.setText("/");
        dividBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dividBtnActionPerformed(evt);
            }
        });
        jPanel3.add(dividBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 58, 43));

        substracBtn.setBackground(new java.awt.Color(255, 255, 255));
        substracBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        substracBtn.setForeground(new java.awt.Color(0, 0, 0));
        substracBtn.setText("-");
        substracBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                substracBtnActionPerformed(evt);
            }
        });
        jPanel3.add(substracBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 58, 43));

        fourBtn.setBackground(new java.awt.Color(255, 255, 255));
        fourBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fourBtn.setForeground(new java.awt.Color(0, 0, 0));
        fourBtn.setText("4");
        fourBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourBtnActionPerformed(evt);
            }
        });
        jPanel3.add(fourBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 58, 43));

        oneBtn.setBackground(new java.awt.Color(255, 255, 255));
        oneBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        oneBtn.setForeground(new java.awt.Color(0, 0, 0));
        oneBtn.setText("1");
        oneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneBtnActionPerformed(evt);
            }
        });
        jPanel3.add(oneBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 58, 43));

        sixBtn.setBackground(new java.awt.Color(255, 255, 255));
        sixBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sixBtn.setForeground(new java.awt.Color(0, 0, 0));
        sixBtn.setText("6");
        sixBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixBtnActionPerformed(evt);
            }
        });
        jPanel3.add(sixBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 58, 43));

        threeBtn.setBackground(new java.awt.Color(255, 255, 255));
        threeBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        threeBtn.setForeground(new java.awt.Color(0, 0, 0));
        threeBtn.setText("3");
        threeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeBtnActionPerformed(evt);
            }
        });
        jPanel3.add(threeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 58, 43));

        fiveBtn.setBackground(new java.awt.Color(255, 255, 255));
        fiveBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fiveBtn.setForeground(new java.awt.Color(0, 0, 0));
        fiveBtn.setText("5");
        fiveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveBtnActionPerformed(evt);
            }
        });
        jPanel3.add(fiveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 58, 43));

        field_number.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        field_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_numberActionPerformed(evt);
            }
        });
        jPanel3.add(field_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 36));

        Jprogres.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.add(Jprogres, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 270, 20));

        deleteBtn.setBackground(new java.awt.Color(255, 102, 102));
        deleteBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(0, 0, 0));
        deleteBtn.setText("CLR");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel3.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 60, 40));

        list_calc.setBackground(new java.awt.Color(255, 255, 255));
        list_calc.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        list_calc.setForeground(new java.awt.Color(0, 0, 0));
        list_calc.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(list_calc);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 100, 220));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\ow\\src\\main\\java\\myApplicationDesktop\\lov.png")); // NOI18N
        jLabel6.setText("Made With JSwing");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\ow\\src\\main\\java\\myApplicationDesktop\\red.png")); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\ow\\src\\main\\java\\myApplicationDesktop\\yello.png")); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\ow\\src\\main\\java\\myApplicationDesktop\\green.png")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel4.setText("X Kalkulator");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(98, 98, 98)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        StringBuilder gSb = new StringBuilder();
        gSb.append(field_number.getText().toString());
        if(field_number.getText().length() != 0){
            gSb.delete(gSb.length() - 1,gSb.length());
            field_number.setText(gSb.toString());
        } else{
            field_number.setText("");
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void field_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_numberActionPerformed

    }//GEN-LAST:event_field_numberActionPerformed

    private void fiveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveBtnActionPerformed
        // TODO add your handling code here:

        field_number.setText(field_number.getText() + "5");
    }//GEN-LAST:event_fiveBtnActionPerformed

    private void threeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeBtnActionPerformed
        // TODO add your handling code here:
        field_number.setText(field_number.getText() +"3");
    }//GEN-LAST:event_threeBtnActionPerformed

    private void sixBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixBtnActionPerformed
        // TODO add your handling code here:

        field_number.setText(field_number.getText() + "6");
    }//GEN-LAST:event_sixBtnActionPerformed

    private void oneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneBtnActionPerformed
        // TODO add your handling code here:
        field_number.setText(field_number.getText() + "1");
    }//GEN-LAST:event_oneBtnActionPerformed

    private void fourBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourBtnActionPerformed
        // TODO add your handling code here:

        field_number.setText(field_number.getText() + "4");
    }//GEN-LAST:event_fourBtnActionPerformed

    private void substracBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_substracBtnActionPerformed
        // TODO add your handling code here
        field_number.setText(field_number.getText() + "-");
    }//GEN-LAST:event_substracBtnActionPerformed

    private void dividBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dividBtnActionPerformed
        // TODO add your handling code here:
        field_number.setText(field_number.getText() + "/");
    }//GEN-LAST:event_dividBtnActionPerformed

    private void getResultBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getResultBtnActionPerformed
        // TODO add your handling code here:
        String s = field_number.getText().toString();
        if (s.contains("+")) {
            String arr[] = s.split("\\+");
            calculate = Integer.parseInt(arr[0]) + Integer.parseInt(arr[1]);
            field_number.setText(String.valueOf(calculate));
            DLM.addElement(String.valueOf(calculate));
            list_calc.setModel(DLM);

            Jprogres.setValue(calculate);
            Jprogres.setStringPainted(true);
        } else if (s.contains("-")) {
            String arr[] = s.split("\\-");
            calculate = Integer.parseInt(arr[0]) - Integer.parseInt(arr[1]);
    
            field_number.setText(String.valueOf(calculate));
            addNum.add(String.valueOf(calculate));
            DLM.addElement(String.valueOf(calculate));
            list_calc.setModel(DLM);
            Jprogres.setValue(calculate);
            Jprogres.setStringPainted(true);
        } else if (s.contains("/")) {
            String arr[] = s.split("\\/");
            calculate = Integer.parseInt(arr[0]) / Integer.parseInt(arr[1]);
            field_number.setText(String.valueOf(calculate));
            addNum.add(String.valueOf(calculate));
            DLM.addElement(String.valueOf(calculate));
            list_calc.setModel(DLM);

            Jprogres.setValue(calculate);
            Jprogres.setStringPainted(true);
        } else if (s.contains("*")) {
            String arr[] = s.split("\\*");
            calculate = Integer.parseInt(arr[0]) / Integer.parseInt(arr[1]);
            field_number.setText(String.valueOf(calculate));
            DLM.addElement(String.valueOf(calculate));
            list_calc.setModel(DLM);

            Jprogres.setValue(calculate);
            Jprogres.setStringPainted(true);
        }

    }//GEN-LAST:event_getResultBtnActionPerformed

    private void sumBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumBtnActionPerformed
        // TODO add your handling code here
        field_number.setText(field_number.getText() + "+");
    }//GEN-LAST:event_sumBtnActionPerformed

    private void twoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoBtnActionPerformed
        // TODO add your handling code here:
        field_number.setText(field_number.getText() + "2");
    }//GEN-LAST:event_twoBtnActionPerformed

    private void sevenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenBtnActionPerformed
        // TODO add your handling code here:
        field_number.setText(field_number.getText() + "7");
    }//GEN-LAST:event_sevenBtnActionPerformed

    private void nineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineBtnActionPerformed
        // TODO add your handling code here:

        field_number.setText(field_number.getText() + "9");
    }//GEN-LAST:event_nineBtnActionPerformed

    private void multBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multBtnActionPerformed
        // TODO add your handling code here:
        field_number.setText(field_number.getText() + "*");
    }//GEN-LAST:event_multBtnActionPerformed

    private void eightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightBtnActionPerformed
        // TODO add your handling code here:
        field_number.setText(field_number.getText() + "8");
    }//GEN-LAST:event_eightBtnActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        ;
    }//GEN-LAST:event_jLabel2MouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        positionX = evt.getX();
        positionY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        setLocation(evt.getXOnScreen() - positionX, evt.getYOnScreen() - positionY);
    }//GEN-LAST:event_formMouseDragged
    DefaultListModel DLM = new DefaultListModel();
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar Jprogres;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton dividBtn;
    private javax.swing.JButton eightBtn;
    private javax.swing.JTextField field_number;
    private javax.swing.JButton fiveBtn;
    private javax.swing.JButton fourBtn;
    private javax.swing.JButton getResultBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JList<String> list_calc;
    private javax.swing.JButton multBtn;
    private javax.swing.JButton nineBtn;
    private javax.swing.JButton oneBtn;
    private javax.swing.JButton sevenBtn;
    private javax.swing.JButton sixBtn;
    private javax.swing.JButton substracBtn;
    private javax.swing.JButton sumBtn;
    private javax.swing.JButton threeBtn;
    private javax.swing.JButton twoBtn;
    // End of variables declaration//GEN-END:variables
}
